Controllers/EpersoController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;   
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tutorat.Models;

namespace Tutorat.Controllers
{
    // Attribut Authorize = http://stackoverflow.com/questions/22591252/asp-net-mvc4-restrict-all-pages-for-a-non-logged-user
    // Voir partie Jaune du post
    [Authorize]
    public class EpersoController : DefautController
    {
        private Ephec bdd = new Ephec();

        /// <summary>
        /// Contient les informations de l'étudiant récupérées en BDD depuis le mail
        /// </summary>
        /// <returns> Affiche la page info </returns>
        public ActionResult Info()
        {
            etudiant InfoEtudiant = bdd.etudiant.FirstOrDefault(u => u.mail.Contains(System.Web.HttpContext.Current.User.Identity.Name));
            return View(InfoEtudiant);
        }

        /// <summary>
        ///  Affiche la page Cours si l'étudiant n'a pas de cours OU CoursInscrits si il en a
        /// </summary>
        /// <returns> Affiche la page en fonction de la variable session créée à la connexion</returns>
        public ActionResult Cours()
        {
           
            ViewBag.DDCours = GenereCours();

            if ((int)Session["nbCoursInscrit"] != 0)
            {
                return RedirectToAction("CoursInscrits");
            }
            //Sinon remplir sa liste de cours & résultats.
            return View();
        }

        /// <summary>
        /// Tableau des cours et résultats de l'étudiant
        /// </summary>
        /// <returns> Affiche la page avec la liste des cours de l'étudiant</returns>
        public ActionResult CoursInscrits()
        {
            int id = getIdEtudiant();

            // Following : http://stackoverflow.com/questions/16793767/net-mvc-passing-linq-data-from-controller-to-view
            // More Edits part !! Perfect <3

            var etuCours = from c in bdd.cours
                                   where c.etudiant.Any(e => e.etudiant_id == id)
                                   select new resultCours { cours_id = c.cours_id, libelle = c.libelle, code = c.code, annee = c.annee };
            ViewBag.etuR = etuCours;

            // Créé un objet resultCours pour l'affichage de la liste des cours et résultats de l'étudiant
            IEnumerable<resultCours> etuResult = from e in bdd.etudiant
                                                 from c in bdd.cours
                                                 from er in bdd.etuResult
                                                 where e.etudiant_id == id && e.etudiant_id == er.etudiant_id
                                                 where c.cours_id == er.cours_id
                                                 select new resultCours { libelle = c.libelle, annee = c.annee, code = c.code, cote = er.cote, cours_id = er.cours_id };

            listCoursResult list = new listCoursResult()
            {
                Items = etuResult.AsEnumerable(),

            };
            return View(list);

        }

        /// <summary>
        ///  Récupèré les listes de string contenant les ID des cours et les cotes entrées (si existent) pour les ajouter en BDD etuCours et etuResult (si existe)
        /// </summary>
        /// <param name="liste"> récupère les cours et résultats entrés par l'étudiant </param>
        /// <returns> Retourne à la page index si les données ont correctement été récupéré</returns>
        [HttpPost]
        public ActionResult Cours(listCoursResult liste)
        {
            int id = getIdEtudiant();
            ViewBag.DDCours = GenereCours();

            string[] DDCours = Request.Form.GetValues("DDCours");
            string[] coteCours = Request.Form.GetValues("coteCours");

            List<cours> listc = new List<cours> { };
            for (int i = 0; i < DDCours.Length; i++)
            {

                DDCours = DDCours.Where(x => !string.IsNullOrEmpty(x)).ToArray();
                coteCours = coteCours.ToArray();

                int cotetmp;
                if(coteCours[i] == null || coteCours[i] == "")
                {
                    cotetmp = -1;
                } else {
                    cotetmp = int.Parse(coteCours[i]); 
                }

                if (cotetmp != -1)
                {
                    //Ajoute l'étudiant dans la bdd etuResult QUE si il a une cote pour le cours.
                    etuResult etuRes = new etuResult();
                    etuRes.etudiant_id = id ;
                    etuRes.cours_id = int.Parse(DDCours[i]);
                    etuRes.cote = cotetmp;
                    bdd.etuResult.Add(etuRes);
                }

                //Ajout des cours de l'étudiant
                int codeCours = int.Parse(DDCours[i]);
                cours c = bdd.cours.FirstOrDefault(u => u.cours_id == codeCours);
                listc.Add(c);
            }
 
            //Ajoute la liste de cours dans la table etuCours de l'étudiant
            etudiant etu = bdd.etudiant.FirstOrDefault(e => e.etudiant_id == id);
            etu.cours = listc;
            bdd.SaveChanges();
            if (listc.Any())
            {
                Session["nbCoursInscrit"] = etu.cours.Count();
            }
            // Ajouter le nombre de cours
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Explications()
        {
            return View();
        }
    }
}

Controllers/coursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tutorat.Models;

namespace Tutorat.Controllers
{
    public class coursController : Controller
    {
        private Ephec db = new Ephec();

        // GET: cours
        public ActionResult Index()
        {
            return View(db.cours.ToList());
        }   

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Eperso/Cours.cshtml
@{
    ViewBag.Title = "Cours";
}
@section JavaScript
{
    <script type="text/javascript" src="@Url.Content("/Scripts/registerScripts.js")"></script>
}
        <!-- AJOUT POUR LES COURS -->
<hr />
<h2>Inscription aux cours et ajout des résultats</h2>
<hr />

<h4>Concernant les étudiants <b>demandeur</b> </h4>
<p>Dans cette page vous pourrez remplir les cours que vous avez <b>cette</b> année ainsi que les résultats s'y rapportant si vous en avez, sinon laisser le champ Cote vide.</p>
<p>C'est dans cette liste que vous pourrez choisir les cours pour vos futurs demandes de tutorats</p>
<br />

<h4>Concernant les étudiants candidats <b>tuteur</b> </h4>
<p>Remplissez dans cette page les cours que vous avez la possibilité et/ou aimeriez donner. </p>
<p>Ajoutez-y les cotes s'y rapportant, même si celles-ci sont inférieurs aux résultats nécessaires pour donner un tutorat.</p>
<p>Vous pourrez, dans la page d'offre de tutorat, ajouter un commentaire à l'attention de Madame Allen.</p>
<br />


@using (Ajax.BeginForm("Cours", "Eperso", new AjaxOptions()
{
    //HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "dane"
}))
{

    <div class="dropdown ">
        <div class="form-group">
            <div class="col-md-2 control-label">
                Choix du cours :
            </div>
            <div class="dropdown-toggle col-md-5">
                @Html.DropDownList("DDCours")
            </div>
            <div class="col-md-5">
                Cote :
                @Html.TextBox("coteCours", "", new { @type = "number", @min = "0", @max = "20" })

                <span style="cursor:pointer; color:green;" onclick="addNew();">ADD</span>
                <span style="cursor:pointer; color:red;" class="delete" onclick="remove(this)">REMOVE</span>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clonecontainer"></div>
    <input type="submit" value="Soumettre" onclick="reload()"/>
}

Views/Eperso/CoursInscrits.cshtml
@model Tutorat.Models.listCoursResult
@{
    ViewBag.Title = "Mes Cours";
}

<h3> Mes Cours</h3>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title">Cours</h1>
            </div>
            <div class="panel-body">
                <table id="assets-data-table"
                       class="table table-striped table-bordered"
                       style="width:100%">
                    <thead>
                        <tr>
                            <!-- <th>cours_id</th> -->
                            <th>libelle</th>
                            <th>code</th>
                            <th>annee</th>
                            <th>cote</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                        <tr>
                            <td>@item.libelle </td>
                            <td>@item.code </td>
                            <td>@item.annee </td>
                            <td>
                                @if (@item.cote == null)
                                {
                                    @Html.Display("");
                                }
                                else
                                {
                                    @item.cote
                                }
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Si l'etudiant a pas de cours : afficher les cours et les résultats -->
<h3> Mes résultats : </h3>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title">Cours</h1>
            </div>
            <div class="panel-body">
                <table id="assets-data-table"
                       class="table table-striped table-bordered"
                       style="width:100%">
                    <thead>
                        <tr>
                            <!-- <th>cours_id</th> -->
                            <th>ID - libelle</th>
                            <th>code</th>
                            <th>annee</th>
                            <th>cote</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{var i = 0;}
                        @foreach (var item in ViewBag.etuR)
                        {
                            <tr>
                                <td>@item.cours_id - @item.libelle </td>
                                <td>@item.code </td>
                                <td>@item.annee </td>
                                <td>
                                    @if (@item.cote == null)
                                {
                                    @Html.Display("");
                                }
                                else
                                {
                                    @item.cote
                                }
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Eperso/Explications.cshtml
@{
    ViewBag.Title = "Explications d'ePerso";
}

<h2>Explications d'ePerso</h2>

<p> Voici la première partie du travail. Celle-ci n'était pas demandée puisque l'idée est d'intégrer le tutorat à la plateforme existante (ePerso).</p>
<p> J'ai malgré tout décidé de suivre la base de données et de compléter le plus de tables. </p>

<p> Une fois inscrit vous pouvez : </p>

<h3> Regarder vos informations personnelles</h3>
<p> Il s'agit des informations que vous avez entrées lors de votre inscription sur le site, un peu à la manière du véritable onglet dans ePerso.</p>


<h3> Ajout / visualisation des cours et résultats </h3>
<p> Si vous n'avez pas encore renseigné vos cours (nécessaire pour la suite), vous pouvez les ajouter à cette page. Si cela a déjà été fait, vous pouvez voir vos cours ainsi que les résultats associés à cette page.</p>


<p> Attention, dans la réalité le compte est créé par l'école. Il n'est pas nécessaire de tenir compte de cette partie et du contrôleur associé pour la migration. </p>
<p> Je n'ai créé que ce qui m'était utile pour la suite du programme (c'est à dire les cours et les résultats si il y en).</p>

Views/Eperso/Info.cshtml
@model Tutorat.Models.etudiant
    <!-- Page finie. -->

@{
    ViewBag.Title = "Informations de l'étudiant connecté";
}

<h2>@ViewBag.Title</h2>
<p> Cette page fournie les informations avec lesquelles l'étudiant s'est inscrit. La page sera utilisée en cas de test grandeur réel.</p>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matricule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.section)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.section)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.annee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.annee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.groupe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

    </dl>
</div>
<!-- TO DELETE -->
<hr />
<div>
    <h2> Valeurs de la variable session : </h2>

    <p> Ces valeurs sont assignées à la connexion de l'utilisateur</p>
    @foreach (string i in Session.Contents)
    {
        <p>
            La variable "@i" a pour valeur @Session[i].ToString().
        </p>
    }
</div>