Controllers/TutoratController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Tutorat.Models;

namespace Tutorat.Controllers
{
    // Attribut Authorize = http://stackoverflow.com/questions/22591252/asp-net-mvc4-restrict-all-pages-for-a-non-logged-user
    // See Yellow in answer's post
    [Authorize]
    public class TutoratController : DefautController // extend pour accéder aux fonction de DefautController
    {
        private Ephec db = new Ephec();
        private EphecTemp bddtemp = new EphecTemp();

        /// <summary>
        /// Demande de tutorat :
        /// Affiche une liste de cours auxquels l'étudiant connecté peut s'inscrire
        /// </summary>
        /// <returns> Une vue </returns>
        // GET: Tutorat/Demande
        public ActionResult Demande()
        {
            int id = getIdEtudiant();

            //Tous les cours de l'étudiant
            var coursEtu =
                 db.etudiant
                    .Single(e => e.etudiant_id == id)
                    .cours.Select(c => new resultCours
                    {
                        libelle = c.libelle,
                        cours_id = c.cours_id,
                        annee = c.annee,
                        code = c.code

                    }).ToList();

            //Les cours ou l'étudiant à des résultats
            var coursEtuResult = (from e in db.etudiant
                                 from er in db.etuResult
                                 from c in db.cours
                                 where e.etudiant_id == er.etudiant_id
                                 && c.cours_id == er.cours_id
                                 && e.etudiant_id == id
                                 && er.cote > 9
                                  select (new resultCours
                                 {
                                     libelle = c.libelle,
                                     cours_id = c.cours_id,
                                     annee = c.annee,
                                     code = c.code

                                 })).ToList();

            //Tous les cours de l'étudiant - les cours ou l'étudiant à des résultats > 9
            var result = coursEtu.Where(p => !coursEtuResult.Any(x => x.cours_id == p.cours_id)).ToList();

            //Ajout des cours "Table de conversation", "remédiation Fr", "Extra académiques"    (pour l'exemple je n'en ai ajouté qu'un des 3)
            //result.Add(new resultCours { libelle = "Table de Conversation", cours_id = 1002, annee=1, code="HELP01"});
            ViewBag.listCoursDemande = result;
            return View();
        }

        /// <summary>
        /// Gestion des demandes de l'étudiant : envoie les cours sélectionnés en BDDtemp
        /// </summary>
        /// <param name="model"> La liste de cours </param>
        /// <returns> Redirige à l'index </returns>
        [HttpPost]
        public ActionResult Demande(listeDemandeTmp model)
        {

            for (int i = 0; i < model.Items.Count(); i++)
            {
                if (model.Items[i].select == true)
                {
                    // OBLIGER DE CREER LES OBJETS ICI  !!! 
                    /* This problem happens because you are referencing the same object more than once. This is not a limitation of EF, but rather a safety feature to ensure you are not inserting the same object with two different IDs. 
                     * So to achieve what you are trying to do, is simply create a new object and add the newly created object to the database.
                     ** This issue often happens inside loops. If you are using a while or foreach loop, make sure to have the New Created Object INSIDE the loop body.
                     * */
                    demandeurtmp dtemp = new demandeurtmp();
                    demandeurCourstmp dctemp = new demandeurCourstmp();

                    int demandeurID;
                    // Si table est vide : tuteurID = 0, sinon retourne le tuteur_id le plus grand
                    if (!bddtemp.demandeurtmp.Any())
                    {
                        demandeurID = 0;
                    }
                    else
                    {
                        demandeurID = bddtemp.demandeurtmp.Max(u => u.demandeur_id);
                    }

                    model.Items[i].matricule = getMatricule();
                    Session["EnDemande"] = true;
                    dtemp.matricule = model.Items[i].matricule;
                    dtemp.dateInsc = DateTime.Now;
                    dtemp.demandeur_id = demandeurID + 1;

                    dctemp.demandeur_id = dtemp.demandeur_id;
                    dctemp.cours_id = model.Items[i].cours_id;
                    dctemp.commentaire = model.Items[i].commentaire;
                    dctemp.matriculeTuteurPref = model.Items[i].matriculeTuteurPref;
                    enregDemande(dtemp, dctemp);
                }

            }

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Ajout des demandeurstmp et demandeurCourstmp en BDDtmp + sauvegarde de la BDDtmp
        /// </summary>
        /// <param name="d"> demandeurtmp </param>
        /// <param name="dc"> demandeurCourstmp</param>
        public void enregDemande(demandeurtmp d, demandeurCourstmp dc)
        {
            bddtemp.demandeurtmp.Add(d);
            bddtemp.demandeurCourstmp.Add(dc);
            bddtemp.SaveChanges();

        }

        /// <summary>
        /// Affiche la page d'explication des tutorats
        /// </summary>
        /// <returns> Une vue </returns>
        // GET: Tutorat/Explanation
        public ActionResult Explications()
        {
            return View();
        }

        /// <summary>
        /// Offre de tutorat :
        /// Affiche une liste de cours auxquels l'étudiant connecté peut s'inscrire
        /// </summary>
        /// <returns> Une vue </returns>
        // GET: Tutorat/Offre
        public ActionResult Offre()
        {
            int id = getIdEtudiant();
            //Affichage des cours auxquels l'étudiant est inscrit cette année et ou il a une cote supérieure à 10 !!
            var coursEtu =
                from e in db.etudiant
                from er in db.etuResult
                from c in db.cours
                where e.etudiant_id == er.etudiant_id
                && c.cours_id == er.cours_id
                && e.etudiant_id == id
                && er.cote >= 14
                select new resultCours
                {
                    libelle = c.libelle,
                    cours_id = c.cours_id,
                    annee = c.annee,
                    code = c.code,
                    cote = er.cote
                };
            List<resultCours> list = coursEtu.ToList();

            string matricule = getMatricule();
            //TuteurIdTmp : Voir si l'étudiant est deja en Offre de tutorat dans la bdd temp :
            int[] tuteuridstmp = bddtemp.tuteurtmp.Where(t => t.matricule == matricule).Select(t => t.tuteur_id).ToArray();
            int[] tuteurids = bddtemp.tuteurtmp.Where(t => t.matricule == matricule).Select(t => t.tuteur_id).ToArray();
            
            //Vérif : si l'étudiant est déjà en Offre de tutorat (mais pas encore de tutorat trouvé) : 
            ViewBag.listCoursOffre = coursEtu; 

            if(tuteuridstmp.Length != 0 || tuteurids.Length != 0)
            { ViewBag.DejaTuteur = true; } else { ViewBag.DejaTuteur = false; }

            return View();
        }

        /// <summary>
        /// Gestion des demandes de l'étudiant : envoie les cours sélectionnés en BDDtemp
        /// </summary>
        /// <param name="model"> La liste de cours </param>
        /// <returns> Redirige à l'index </returns>
        [HttpPost]
        public ActionResult Offre(listeTuteurTmp model)
        {
            for (int i = 0; i < model.Items.Count(); i++)
            {
                if (model.Items[i].select == true)
                {
                    tuteurtmp ttemp = new tuteurtmp();
                    tuteurCourstmp tctemp = new tuteurCourstmp();

                    int tuteurID;
                    // Si table est vide : tuteurID = 0, sinon retourne le tuteur_id le plus grand
                    if (!bddtemp.tuteurtmp.Any())
                    {
                        tuteurID = 0;
                    } else
                    {
                        tuteurID = bddtemp.tuteurtmp.Max(u => u.tuteur_id);
                    }

                    model.Items[i].matricule = getMatricule();
                    Session["EnOffre"] = true;
                    ttemp.matricule = model.Items[i].matricule;
                    ttemp.dateInsc = DateTime.Now;
                    ttemp.tuteur_id = tuteurID + 1;

                    tctemp.tuteur_id = ttemp.tuteur_id;
                    tctemp.cours_id = model.Items[i].cours_id;
                    tctemp.commentaire = model.Items[i].commentaire;
                    enregTuteur(ttemp, tctemp);
                }
            }
            return RedirectToAction("Index", "Home");
        }



        /// <summary>
        /// Ajout des tuteurtmp et tuteurCourstmp en BDDtmp + sauvegarde de la BDDtmp
        /// </summary>
        /// <param name="t"> tuteurtmp </param>
        /// <param name="tc"> tuteurCourstmp</param>
        public void enregTuteur(tuteurtmp t, tuteurCourstmp tc)
        {
            bddtemp.tuteurtmp.Add(t);
            bddtemp.tuteurCourstmp.Add(tc);
            bddtemp.SaveChanges();
        }

        /// <summary>
        /// Affichage du guide pratique
        /// </summary>
        /// <returns> Une Vue </returns>
        // GET: Tutorat/GuidePratique
        public ActionResult GuidePratique()
        {
            return View();
        }

Views/Tutorat/ConfirmationPage.cshtml
@{
    ViewBag.Title = "ConfirmationPage";
}

<h2>Confirmation Page</h2>

Votre @TempData["type"] a bien été pris en compte, vous allez maintenant être redirigé vers la page d'accueil.

Views/Tutorat/Explications.cshtml
@{
    ViewBag.Title = "Explications des tutorats";
}

<h2>Explications de la partie tutorat</h2>

<h3> Guide Pratique</h3>
<p> L'onglet va fournir des informations aux étudiants souhaitant entrer dans le programme de tutorat.</p>

<p> Vous pouvez y trouver : l'évolution du tutorat à l'Ephec depuis qu'il a été mis en place, des explications concernant qui peut être tuteur, quel est son rôle, à qui s'adresse le tutorat, ... <br />
    Une liste d'outils pratiques pour la bonne organisation du tutorat mais aussi une foire aux questions et finalement, l'adresse du responsable pour les tutorats.</p>

<h3> Offre et Demande de tutorat</h3>
<p> Une fois connecté et après avoir ajouté vos cours, vous pouvez vous inscrire aux tutorats :</p>


<p> Les étudiants demandeurs de tutorat se rendront dans l'onglet demande. De là, ils pourront voir les cours dans lesquels ils peuvent demander un tutorat.</p>
<p> Ne s'affichent ici que les cours où l'étudiant n'a pas de cote et/ou les cours où il a eu des résultats inférieurs à 10 / 20.</p>

<br/>
<p> Les étudiants offrant leur service pour les tutorats iront dans l'onglet Offre. De là, pareil que pour les demandeurs : les cours où ils ont eu une cote supérieure à 12/20 s'afficheront. </p>

<br/>
<p> Une fois les propositions effectuées, les étudiants seront redirigés vers la page d'accueil si tout s'est bien passé.</p>

<h3> Encodage des prestations </h3>
<p> Un dernier onglet concerne l'encodage des prestations : si le tutorat a été accepté et que l'étudiant s'est vu attribué un étudiant à aider, il pourra encode ses prestations. </p>

Views/Tutorat/MesPrestations.cshtml
@model Tutorat.Models.listePrestationtmp

@{
    ViewBag.Title = "Mes Prestations";
}

<h2>Mes Prestations</h2>

<p> Page d'ajout des prestations étudiants </p>

<p style="color:red"> Attention : tous les champs doivent être remplis pour que la prestation soit encodée.</p>

@using (Ajax.BeginForm("MesPrestations", "Tutorat", new AjaxOptions()
                        //{
                        //HttpMethod = "POST",
                        //  InsertionMode = InsertionMode.Replace,
                        // UpdateTargetId = "dane"
                        //}
                        ))
{
    int i = 0;
    foreach (var id in @ViewBag.infos)
    {
        @Html.HiddenFor(m => m.Items[i].tuteur_id, new { @Value = @id.tuteur_id });
        @Html.HiddenFor(m => m.Items[i].tutorat_id, new { @Value = @id.tutorat_id });
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary list-panel" id="list-panel">
                    <div class="panel-heading list-panel-heading">
                        <h1 class="panel-title list-panel-title">@id.cours_id - @id.cours_libelle avec l'étudiant @id.nomPrenomDemandeur (@id.matriculeDemandeur)</h1>
                    </div>
                    <div class="panel-body" >
                        <div class='@(string.Format("cours{0}", i))'>
                            <div class="form-group">
                                <p style="color:red;"> Durée restante pour ce tutorat : @id.dureeRestante min</p>
                                <p> La durée ne peut pas dépasser 10h pour un tutorat (hors accord avec le Service d'Aide à la Réussite) et 3h par jour par tutorat. Tout dépassement ne sera pas considéré sans accord.</p>
                                Date : @Html.TextBoxFor(m => m.Items[i].datePrestation, "{0:dd/MM/yyyy}" ,new { type = "date", max = "DateTime.Now.ToString('d')"})
                                

                                Durée de prestation: @Html.TextBoxFor(m => m.Items[i].dureePrestation, new { @type = "number", min = "0", max = "180" })


                                Compte rendu : @Html.TextAreaFor(m => m.Items[i].compteRendu, new { maxlength = "512", placeholder = "Max 512 caractères, soyez bref!", rows = "5", cols = "50" })

                                <br />
                                @Html.ValidationMessageFor(m => m.Items[i].dureePrestation, "", new { @class = "text-danger" })
                                <br />
                                @Html.ValidationMessageFor(m => m.Items[i].datePrestation, "", new { @class = "text-danger" })
                                <br />
                                @Html.ValidationMessageFor(m => m.Items[i].compteRendu, "", new { @class = "text-danger" })
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clonecontainer"></div>
                    </div>
                </div>

            </div>
        </div>
        i++;
    }
    <p class="text-danger"  >
        <script type="text/javascript">
            $(".text-danger").ready(function () {
                $(".text-danger").fadeOut(10000);
            });
        </script>
       @ViewData["save"]
    </p>
    <input type="submit" value="Soumettre"/>
}

Views/Tutorat/Offre.cshtml
@model Tutorat.Models.listeDemandeTmp

@{
    ViewBag.Title = "Offre";
}

<h2> Offre de Tutorat : </h2>

<p> Sur cette page vous allez pouvoir remplir votre offre de tutorat pour l'année en cours. </p>
<p> Les cours sont ceux que vous avez ajouté dans l'onglet Cours de Eperso. </p>

<h3> Cap vers la réussite en 1ère bac à l’<b> EPHEC</b> </h3>

<p>
    Après la mise en relation avec ton étudiant, les coordonnées de celui-ci te seront envoyées sur ton adresse eperso.
    <b style="text-decoration:underline">Vérifie régulièrement tes mails</b>
</p>
@if(ViewBag.DejaTuteur != false)
{
    <p style="color:red;"> Attention, vous êtes déjà tuteur ou en proposition de tutorat pour un ou plusieurs cours !</p>
}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title">Offre de tutorat pour les cours suivants :</h1>
            </div>
            <!-- BEGIN FORM : -->
            @using (Ajax.BeginForm("Offre", "Tutorat",
                new AjaxOptions { LoadingElementId = "loader", OnSuccess = "onSuccess", }))
            {
                <div class="panel-body">
                    <table id="assets-data-table"
                           class="table table-striped table-bordered"
                           style="width:100%">
                        <thead>
                            <tr>
                                <th>ID - Libelle du cours</th>
                                <th>Code</th>
                                <th>Annee</th>
                                <th>Résultats</th>
                                <th>Commentaire (facultatif)</th>
                                <th>Proposition de tutorat</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int i = 0;}
                            @foreach (var person in ViewBag.listCoursOffre)
                            {
                                <tr>
                                    <td>@Html.HiddenFor(m => m.Items[i].cours_id, new { @Text = @person.libelle, @Value = @person.cours_id }) @person.cours_id - @person.libelle </td>
                                    <td>@person.code</td>
                                    <td>@person.annee</td>
                                    <td>@person.cote</td>
                                    <td>@Html.TextAreaFor(m => m.Items[i].commentaire, new { maxlength = "500", placeholder = "Max 500 caractères, soyez bref!", rows = "7", cols = "50" })</td>
                                    <td>@Html.CheckBoxFor(m => m.Items[i].select)</td>
                                </tr>
                                i++;
                            }
                        </tbody>
                    </table>
                </div>
                <input type="submit" value="Soumettre" onclick="alert('Votre offre de tutorat a correctement été enregistrée');"/>
                                }
        </div>
    </div>
</div>